name: "notion-commit-wf"
author: Misery7100
description: "Export last commit into Notion with commit message parse."
inputs:
  SECRET_GITHUB:
    description: "GitHub Personal Token"
    required: true
  NOTION_API_KEY:
    description: "Notion API Key"
    required: true
  NOTION_DATABASE:
    description: "Notion Database ID for GitHub commits"
    required: true
  TASKS_DATABASE:
    description: "Tasks Database ID to build relation with"
    required: true
  OWNER:
    description: "Repo owner"
    required: true
  REPO:
    description: "Repo name"
    required: true
  REFS:
    description: "Refs to get commit from"
    required: true

runs:
  using: node20
  main: index.js
branding:
  icon  : "git-branch"
  color : "gray-dark"